project:
  type: website

website:
  title: "Data Science with Python"
  navbar:
    right:
      - href: notebooks.qmd
        text: Notebooks
      - href: slides.qmd
        text: Slides

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



