project:
  type: website

website:
  title: "Data Science with Python"
  navbar:
    right:
      - href: notebooks.qmd
        text: Notebooks
      - href: slides.qmd
        text: Slides
  page-footer:
    center:
      - icon: github
        href: https://github.com/harisonmg
      - icon: twitter 
        href: https://twitter.com/harisonmg

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



